name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter a name'
        required: true
        default: 'World'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello ${{ inputs.name }}"